title: "Hyperspace - Jekyll"

description: >
  Just another fine responsive site template designed by [HTML5 UP](http://html5up.net)
  
  and released for free under the [Creative Commons](http://html5up.net/license).

show_excerpts: true
# excerpt_separator: <!--more-->  ## you can specify your own separator.


## add your contact informations / or not : will appear on the home page (last section: get in touch)

contacts:
  address: 12345 Somewhere Road 654<br />
             Nashville, TN 00000-0000<br /> 
             USA
  phone: (000) 000-0000  
  email: some@email.com
  socials:
    github: dadatoa
    instagram: dadatoa
    facebook: dadatoa

# présentation de la home page
homepage-sections:
  - _home-sections/intro.md
  - _home-sections/list-posts.md
  - _home-sections/features.md
  - _home-sections/contact-form.md

plugins:
  - jekyll-seo-tag # 
  - jemoji #

# decommenter la ligne source pour que jekyll ne compile le site qu'à partir du contenu du dossier spécifié
# source: dossier/ 

# exclude : contient tout les fichier non nécessaire à Jekyll pour éviter qu'ils ne soient copier ds le repertoire de deploy
exclude : [
  .jekyll-cache,
  .gitignore,
  .gitpod.Dockerfile,
  .gitpod.yml,
  docker-compose.yml,
  Gemfile,
  Gemfile.lock,
  ]

# disable_disk_cache: BOOL - évite la création d'un repertoire de cache type .jekyll-cache
disable_disk_cache: true

collections:
  - home-sections
